version: '3.8'
services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: memgpt
    ports:
      - "5455:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data  # Bind mount to local data directory
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   # Add initialization script

